import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,existsSync,symlinkSync,renameSync,linkSync,fsyncSync,fstatSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFileSync} from 'node:child_process';
import {inspectCleanup,applyCleanup} from '../extensions/delivery/cleanup.mjs';
import {lifecyclePreflight} from '../extensions/delivery/io.mjs';
const git=(root,...args)=>execFileSync('git',['-C',root,...args],{encoding:'utf8',stdio:['ignore','pipe','pipe']});
function fixture(){const dir=mkdtempSync(join(tmpdir(),'delivery-cleanup-test-')),root=join(dir,'repo');mkdirSync(root);git(root,'init','-b','main');writeFileSync(join(root,'tracked'),'baseline');git(root,'add','tracked');git(root,'-c','user.name=Test','-c','user.email=test@example.invalid','commit','-m','fixture');mkdirSync(join(root,'generated'));writeFileSync(join(root,'generated','one'),'preserve me');writeFileSync(join(root,'other'),'other');return root;}
const inspect=(root,paths=['generated'])=>inspectCleanup(root,paths,'session');
test('inspect is read only, inventories exact contents and binds an external recovery destination',()=>{const root=fixture(),c=inspect(root);assert.equal(c.repository,root);assert.equal(c.session,'session');assert.match(c.token,/^[a-f0-9-]+$/);assert.equal(c.inventory.find(e=>e.path==='generated/one').type,'file');assert.equal(existsSync(c.backup),false);assert.ok(!c.backup.startsWith(root+'/'));assert.equal(readFileSync(join(root,'generated/one'),'utf8'),'preserve me');});
test('apply relocates only inspected paths and records durable recovery mapping before mutation',()=>{const root=fixture(),c=inspect(root),journal=[];const r=applyCleanup(root,c,'session',{journal:e=>journal.push(e)});assert.equal(existsSync(join(root,'generated')),false);assert.equal(readFileSync(r.moves[0].destination+'/one','utf8'),'preserve me');assert.equal(readFileSync(join(root,'other'),'utf8'),'other');assert.ok(existsSync(join(c.backup,'manifest.json')));assert.equal(journal[0].phase,'prepared');assert.equal(r.phase,'complete');assert.match(r.status,/other/);assert.throws(()=>applyCleanup(root,c,'session'),/changed|exist|missing/i);});
for(const paths of [['.'],['/tmp'],['../repo'],['generated/../other'],['generated/'],['generated','generated/one'],['generated','generated'],['.git'],['.git/config'],['tracked'],['*'],['generated\\one']])test(`reject unsafe or tracked scope ${JSON.stringify(paths)}`,()=>{assert.throws(()=>inspect(fixture(),paths));});
for(const change of ['content','inventory','branch','head','index','session','symlink','ancestor','hardlink'])test(`reject stale candidate: ${change}`,()=>{const root=fixture(),c=inspect(root);let session='session';if(change==='content')writeFileSync(join(root,'generated/one'),'changed');if(change==='inventory')writeFileSync(join(root,'generated/two'),'new');if(change==='branch')git(root,'switch','-c','elsewhere');if(change==='head')git(root,'-c','user.name=Test','-c','user.email=test@example.invalid','commit','--allow-empty','-m','new');if(change==='index')git(root,'add','generated/one');if(change==='session')session='another';if(change==='symlink'){renameSync(join(root,'generated/one'),join(root,'moved'));symlinkSync('../moved',join(root,'generated/one'));}if(change==='ancestor'){renameSync(join(root,'generated'),join(root,'moved'));symlinkSync('moved',join(root,'generated'));}if(change==='hardlink')linkSync(join(root,'generated/one'),join(root,'alias'));assert.throws(()=>applyCleanup(root,c,session));assert.equal(existsSync(c.backup),false);});
for(const kind of ['symlink','nested','bare','ignored','staged','head-deleted'])test(`inspect protects ${kind}`,()=>{const root=fixture();if(kind==='symlink')symlinkSync('../tracked',join(root,'generated/link'));if(kind==='nested')git(join(root,'generated'),'init');if(kind==='bare')git(join(root,'generated'),'init','--bare');if(kind==='ignored'){writeFileSync(join(root,'.gitignore'),'generated/one\n');}if(kind==='staged')git(root,'add','generated/one');if(kind==='head-deleted'){git(root,'add','generated/one');git(root,'-c','user.name=Test','-c','user.email=test@example.invalid','commit','-m','track');git(root,'rm','--cached','generated/one');}assert.throws(()=>inspect(root));});
test('configured clean drivers are refused without executing them',()=>{const root=fixture();git(root,'config','filter.evil.clean','touch HOOK-RAN');assert.throws(()=>inspect(root),/filter/i);assert.equal(existsSync(join(root,'HOOK-RAN')),false);});
test('partial failure preserves both moved and remaining paths with a prewritten manifest',()=>{const root=fixture(),c=inspect(root,['generated','other']);let count=0;assert.throws(()=>applyCleanup(root,c,'session',{rename:(from,to)=>{if(++count===2)throw new Error('interrupted');renameSync(from,to);}}),/interrupted.*Recovery/s);const manifest=JSON.parse(readFileSync(join(c.backup,'manifest.json'),'utf8'));assert.equal(readFileSync(manifest.moves[0].destination+'/one','utf8'),'preserve me');assert.equal(readFileSync(join(root,'other'),'utf8'),'other');assert.match(readFileSync(join(c.backup,'events.jsonl'),'utf8'),/moved/);});
test('abrupt process exit after rename leaves a durable moving record and recoverable data',()=>{const root=fixture(),c=inspect(root,['generated','other']);const code=`import {applyCleanup} from ${JSON.stringify(new URL('../extensions/delivery/cleanup.mjs',import.meta.url).href)};import {renameSync} from 'node:fs';applyCleanup(${JSON.stringify(root)},${JSON.stringify(c)},'session',{rename:(from,to)=>{renameSync(from,to);process.exit(17);}});`;assert.throws(()=>execFileSync(process.execPath,['--input-type=module','-e',code]),e=>e.status===17);const manifest=JSON.parse(readFileSync(join(c.backup,'manifest.json'),'utf8'));assert.equal(readFileSync(manifest.moves[0].destination+'/one','utf8'),'preserve me');assert.equal(readFileSync(join(root,'other'),'utf8'),'other');assert.match(readFileSync(join(c.backup,'events.jsonl'),'utf8'),/moving/);});
test('EXDEV never falls back to copy/delete and leaves source intact',()=>{const root=fixture(),c=inspect(root);assert.throws(()=>applyCleanup(root,c,'session',{rename:()=>{const e=new Error('cross-device');e.code='EXDEV';throw e;}}),/cross-device/);assert.equal(readFileSync(join(root,'generated/one'),'utf8'),'preserve me');assert.ok(existsSync(join(c.backup,'manifest.json')));});
test('preflight points only untracked dirt toward cleanup',()=>{const root=fixture();assert.throws(()=>lifecyclePreflight(root),/delivery_cleanup/);writeFileSync(join(root,'tracked'),'edited');assert.throws(()=>lifecyclePreflight(root),e=>!e.message.includes('delivery_cleanup'));});
test('backup manifest exists before even the first move and journal failure preserves originals',()=>{const root=fixture(),c=inspect(root);assert.throws(()=>applyCleanup(root,c,'session',{journal:()=>{assert.ok(existsSync(join(c.backup,'manifest.json')));throw new Error('journal unavailable');}}),/journal unavailable.*Recovery/s);assert.ok(existsSync(join(root,'generated/one')));});
test('remaining candidate changed during partial relocation stops safely',()=>{const root=fixture(),c=inspect(root,['generated','other']);assert.throws(()=>applyCleanup(root,c,'session',{rename:(from,to)=>{renameSync(from,to);writeFileSync(join(root,'other'),'new writer');}}),/changed.*Recovery/s);assert.equal(readFileSync(join(root,'other'),'utf8'),'new writer');assert.equal(readFileSync(join(c.backup,'item-0/one'),'utf8'),'preserve me');});
test('aborted apply never creates backup or moves contents',()=>{const root=fixture(),c=inspect(root),abort=new AbortController();abort.abort();assert.throws(()=>applyCleanup(root,c,'session',{signal:abort.signal}));assert.equal(existsSync(c.backup),false);assert.ok(existsSync(join(root,'generated/one')));});
for(const kind of ['git-symlink','gitfile','root-symlink','nested-ancestor','repo-metadata','empty-directory'])test(`protect repository boundaries: ${kind}`,()=>{const root=fixture();let target=root,paths=['generated'];if(kind==='git-symlink'){renameSync(join(root,'.git'),join(root,'metadata'));symlinkSync('metadata',join(root,'.git'));}if(kind==='gitfile'){renameSync(join(root,'.git'),join(root,'metadata'));writeFileSync(join(root,'.git'),'gitdir: metadata\n');}if(kind==='root-symlink'){target=join(root,'../alias');symlinkSync(root,target);}if(kind==='nested-ancestor'){git(join(root,'generated'),'init');paths=['generated/one'];}if(kind==='repo-metadata'){writeFileSync(join(root,'.gitattributes'),'data');paths=['.gitattributes'];}if(kind==='empty-directory'){mkdirSync(join(root,'empty'));paths=['empty'];}assert.throws(()=>inspect(target,paths));});
test('payload files and bottom-up directories are synced before any relocation',()=>{
 const root=fixture();mkdirSync(join(root,'generated/nested'));writeFileSync(join(root,'generated/nested/two'),'nested payload');
 const c=inspect(root,['generated','other']),events=[];
 const expected=['generated/nested/two','generated/one','other','generated/nested','generated'];
 applyCleanup(root,c,'session',{syncPayload:(fd,path)=>{assert.equal(existsSync(c.backup),false);assert.equal(fstatSync(fd).isDirectory(),['generated','generated/nested'].includes(path));fsyncSync(fd);events.push(path);},rename:(from,to)=>{assert.deepEqual(events,expected);renameSync(from,to);}});
 assert.deepEqual(events,expected);
});
for(const failPath of ['generated/one','generated'])test(`payload fsync failure at ${failPath} prevents every relocation`,()=>{
 const root=fixture(),c=inspect(root,['generated','other']);let failedFd;
 assert.throws(()=>applyCleanup(root,c,'session',{syncPayload:(fd,path)=>{if(path===failPath){failedFd=fd;throw new Error('injected payload fsync failure');}fsyncSync(fd);},rename:()=>assert.fail('must not relocate')}),/injected payload fsync failure/);
 assert.notEqual(failedFd,undefined);assert.throws(()=>fstatSync(failedFd),{code:'EBADF'});
 assert.equal(existsSync(c.backup),false);assert.equal(readFileSync(join(root,'generated/one'),'utf8'),'preserve me');assert.equal(readFileSync(join(root,'other'),'utf8'),'other');
});
test('existing backup is never overwritten',()=>{const root=fixture(),c=inspect(root);mkdirSync(c.backup);writeFileSync(join(c.backup,'precious'),'safe');assert.throws(()=>applyCleanup(root,c,'session'));assert.equal(readFileSync(join(c.backup,'precious'),'utf8'),'safe');assert.ok(existsSync(join(root,'generated/one')));});
