import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,mkdirSync,rmSync,chmodSync,readFileSync,renameSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFileSync} from 'node:child_process';
import {defaultBranch,normalizeSlug,branchPlan,commitPlanMessage,workingTreeEvidence,commitApprovedTask,scopedContentFingerprint,fingerprint,firstFreeBranch,createDeliveryBranch,branchState,assertApprovedPaths,clearApprovedStagedPaths} from '../extensions/delivery/io.mjs';
function repo(t){const d=mkdtempSync(join(tmpdir(),'delivery-git-'));t.after(()=>rmSync(d,{recursive:true,force:true}));execFileSync('git',['init','-q','-b','main',d]);writeFileSync(join(d,'a'),'base\n');execFileSync('git',['-C',d,'add','a']);execFileSync('git',['-C',d,'-c','user.name=T','-c','user.email=t@x','commit','-qm','base']);return d;}
test('detects default branch using local fallback',t=>{const d=repo(t);assert.equal(defaultBranch(d),'main');});
test('normalizes safe branch slugs and maps change types',()=>{assert.deepEqual(branchPlan('Add New API!!!','feature'),{prefix:'feature/',slug:'add-new-api',branch:'feature/add-new-api'});assert.equal(commitPlanMessage('bug','Fix issue'),'bug: Fix issue');assert.throws(()=>normalizeSlug('!!!'),/empty/i);});
test('selects the first free numeric branch suffix',t=>{const d=repo(t);for(const name of ['feature/topic','feature/topic-2'])execFileSync('git',['-C',d,'branch',name]);assert.equal(firstFreeBranch(d,{prefix:'feature/',slug:'topic'}),'feature/topic-3');});
test('creates the bound branch only from the clean expected base and detects drift',t=>{const d=repo(t);const base=branchState(d);const created=createDeliveryBranch(d,'feature/new-name',base.head);assert.equal(created.branch,'feature/new-name');assert.throws(()=>createDeliveryBranch(d,'feature/another',base.head),/base branch|base HEAD|worktree changed/i);});
test('working tree evidence is bounded and gives local recovery guidance',t=>{const d=repo(t);writeFileSync(join(d,'a'),'x'.repeat(50000));const evidence=workingTreeEvidence(d,['a']);assert.ok(evidence.length<=40000+300);assert.match(evidence,/repository-local/i);});
test('exact staging treats pathspec magic as a literal filename',t=>{const d=repo(t);const file='literal*[x]?.txt';writeFileSync(join(d,file),'changed\n');const record=commitApprovedTask(d,{changeType:'feature',title:'Magic path',files:[file],expectedHead:execFileSync('git',['-C',d,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),snapshot:scopedContentFingerprint(d,[file])});assert.equal(record.paths[0],file);assert.equal(execFileSync('git',['-C',d,'show','--format=','--name-only',record.hash],{encoding:'utf8'}).trim(),file);});
test('staging rejects pre-staged and outside paths but supports deletion and untracked files',t=>{const d=repo(t);writeFileSync(join(d,'outside'),'x\n');execFileSync('git',['-C',d,'add','outside']);assert.throws(()=>assertApprovedPaths(d,['a']),/Pre-staged/);execFileSync('git',['-C',d,'restore','--staged','outside']);writeFileSync(join(d,'outside'),'x\n');assert.throws(()=>assertApprovedPaths(d,['a']),/outside.*approved/);execFileSync('git',['-C',d,'clean','-qf']);rmSync(join(d,'a'));const deleted=commitApprovedTask(d,{changeType:'bug',title:'Delete path',files:['a'],expectedHead:execFileSync('git',['-C',d,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),snapshot:scopedContentFingerprint(d,['a'])});assert.equal(deleted.paths[0],'a');const file='new*[x]';writeFileSync(join(d,file),'new\n');const next=commitApprovedTask(d,{changeType:'feature',title:'Untracked path',files:[file],expectedHead:deleted.hash,snapshot:scopedContentFingerprint(d,[file])});assert.equal(next.paths[0],file);});
test('directory scopes resolve to the exact changed descendant inventory',t=>{
 const d=repo(t);mkdirSync(join(d,'extensions','netflix-tv'),{recursive:true});mkdirSync(join(d,'extensions','netflix-tv-extra'),{recursive:true});
 writeFileSync(join(d,'extensions','netflix-tv','tracked.js'),'base\n');writeFileSync(join(d,'extensions','netflix-tv-extra','sibling.js'),'base\n');execFileSync('git',['-C',d,'add','extensions']);execFileSync('git',['-C',d,'-c','user.name=T','-c','user.email=t@x','commit','-qm','fixtures']);
 writeFileSync(join(d,'extensions','netflix-tv','tracked.js'),'changed\n');writeFileSync(join(d,'extensions','netflix-tv','new.js'),'new\n');
 assert.deepEqual(assertApprovedPaths(d,['extensions/netflix-tv/']),['extensions/netflix-tv/new.js','extensions/netflix-tv/tracked.js']);
 const base=execFileSync('git',['-C',d,'rev-parse','HEAD'],{encoding:'utf8'}).trim();const snapshot=scopedContentFingerprint(d,['extensions/netflix-tv/']);
 const record=commitApprovedTask(d,{changeType:'feature',title:'Directory scope',files:['extensions/netflix-tv/'],expectedHead:base,snapshot});
 assert.deepEqual(record.paths,['extensions/netflix-tv/new.js','extensions/netflix-tv/tracked.js']);
});
test('directory scopes detect renames and exclude sibling prefixes and literal metacharacter siblings',t=>{
 const d=repo(t);mkdirSync(join(d,'fixtures','tv-catalog'),{recursive:true});writeFileSync(join(d,'fixtures','tv-catalog','old.json'),'{}\n');execFileSync('git',['-C',d,'add','fixtures']);execFileSync('git',['-C',d,'-c','user.name=T','-c','user.email=t@x','commit','-qm','catalog']);
 execFileSync('git',['-C',d,'mv','fixtures/tv-catalog/old.json','fixtures/tv-catalog/new.json']);
 assert.deepEqual(assertApprovedPaths(d,['fixtures/tv-catalog/'],{allowStaged:true}),['fixtures/tv-catalog/new.json','fixtures/tv-catalog/old.json']);
 writeFileSync(join(d,'fixtures','tv-catalogue'),'outside\n');assert.throws(()=>assertApprovedPaths(d,['fixtures/tv-catalog/'],{allowStaged:true}),/tv-catalogue/);
});
test('commits a successful rename using the same no-renames inventory as review',t=>{
 const d=repo(t);mkdirSync(join(d,'scope'));writeFileSync(join(d,'scope','old.txt'),'value\n');execFileSync('git',['-C',d,'add','scope']);execFileSync('git',['-C',d,'-c','user.name=T','-c','user.email=t@x','commit','-qm','old']);
 renameSync(join(d,'scope','old.txt'),join(d,'scope','new.txt'));const base=execFileSync('git',['-C',d,'rev-parse','HEAD'],{encoding:'utf8'}).trim();
 const record=commitApprovedTask(d,{changeType:'feature',title:'Rename path',files:['scope/'],expectedHead:base,snapshot:scopedContentFingerprint(d,['scope/'])});
 assert.deepEqual(record.paths,['scope/new.txt','scope/old.txt']);assert.deepEqual(record.acceptedPaths,record.paths);
});
test('commit staging rejects a deterministic approved-file race before creating a commit',t=>{const d=repo(t);writeFileSync(join(d,'a'),'approved\n');const base=execFileSync('git',['-C',d,'rev-parse','HEAD'],{encoding:'utf8'}).trim();const accepted=scopedContentFingerprint(d,['a']);assert.throws(()=>commitApprovedTask(d,{changeType:'feature',title:'Race path',files:['a'],expectedHead:base,snapshot:accepted,onBeforeStage:()=>writeFileSync(join(d,'a'),'raced\n')}),/snapshot changed|authorization was invalidated/i);assert.equal(execFileSync('git',['-C',d,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),base);assert.equal(execFileSync('git',['-C',d,'diff','--cached','--name-only'],{encoding:'utf8'}).trim(),'');});
test('prepared commit authorization hashes staged content',t=>{const d=repo(t);writeFileSync(join(d,'a'),'changed\n');const base=execFileSync('git',['-C',d,'rev-parse','HEAD'],{encoding:'utf8'}).trim();let prepared;const record=commitApprovedTask(d,{changeType:'feature',title:'Hash path',files:['a'],expectedHead:base,snapshot:scopedContentFingerprint(d,['a']),onPrepared:auth=>{prepared=auth;}});assert.equal(record.acceptedSnapshot,prepared.snapshot);assert.equal(record.acceptedDiffHash,prepared.diffHash);assert.equal(typeof prepared.diffHash,'string');assert.equal(prepared.snapshot.length,64);});
test('failure before staging has no staged-commit authorization and preserves the accepted worktree',t=>{
 const d=repo(t);writeFileSync(join(d,'a'),'changed\n');const base=execFileSync('git',['-C',d,'rev-parse','HEAD'],{encoding:'utf8'}).trim();const snapshot=scopedContentFingerprint(d,['a']);let failure;
 assert.throws(()=>commitApprovedTask(d,{changeType:'feature',title:'Prepare path',files:['a'],expectedHead:base,snapshot,onBeforeStage:()=>{throw new Error('preparation unavailable');}}),error=>{failure=error;return /preparation unavailable/.test(error.message);});
 assert.equal(failure.commitAuthorization,undefined);assert.equal(execFileSync('git',['-C',d,'diff','--cached','--name-only'],{encoding:'utf8'}).trim(),'');assert.equal(scopedContentFingerprint(d,['a']),snapshot);
});
test('hook mutation invalidates commit resume authority',t=>{const d=repo(t);writeFileSync(join(d,'a'),'changed\n');const hook=join(d,'.git','hooks','pre-commit');writeFileSync(hook,'#!/bin/sh\nprintf "hook mutation\\n" > a\nexit 1\n');chmodSync(hook,0o755);const base=execFileSync('git',['-C',d,'rev-parse','HEAD'],{encoding:'utf8'}).trim();let failure;assert.throws(()=>commitApprovedTask(d,{changeType:'feature',title:'Hook path',files:['a'],expectedHead:base,snapshot:scopedContentFingerprint(d,['a'])}),error=>{failure=error;return Boolean(error.commitAuthorization);});assert.throws(()=>commitApprovedTask(d,{changeType:'feature',title:'Hook path',files:['a'],expectedHead:base,snapshot:scopedContentFingerprint(d,['a']),allowStaged:true,expectedAuthorization:failure.commitAuthorization}),/resume authority was invalidated/i);});
test('failed-hook invalidation clears only extension-owned staged paths',t=>{const d=repo(t);writeFileSync(join(d,'a'),'changed\n');const hook=join(d,'.git','hooks','pre-commit');writeFileSync(hook,'#!/bin/sh\nprintf "hook mutation\\n" > a\nexit 1\n');chmodSync(hook,0o755);const base=execFileSync('git',['-C',d,'rev-parse','HEAD'],{encoding:'utf8'}).trim();let failure;assert.throws(()=>commitApprovedTask(d,{changeType:'feature',title:'Clear path',files:['a'],expectedHead:base,snapshot:scopedContentFingerprint(d,['a'])}),error=>{failure=error;return Boolean(error.commitAuthorization);});rmSync(hook);assert.deepEqual(clearApprovedStagedPaths(d,['a']),['a']);assert.equal(execFileSync('git',['-C',d,'diff','--cached','--name-only'],{encoding:'utf8'}).trim(),'');assert.equal(readFileSync(join(d,'a'),'utf8'),'hook mutation\n');});
test('commit failure resumes with the unchanged accepted authorization',t=>{const d=repo(t);writeFileSync(join(d,'a'),'changed\n');const hook=join(d,'.git','hooks','pre-commit');writeFileSync(hook,'#!/bin/sh\nexit 1\n');chmodSync(hook,0o755);const base=execFileSync('git',['-C',d,'rev-parse','HEAD'],{encoding:'utf8'}).trim();let failure;assert.throws(()=>commitApprovedTask(d,{changeType:'feature',title:'Resume path',files:['a'],expectedHead:base,snapshot:scopedContentFingerprint(d,['a'])}),error=>{failure=error;return Boolean(error.commitAuthorization);});rmSync(hook);const record=commitApprovedTask(d,{changeType:'feature',title:'Resume path',files:['a'],expectedHead:base,snapshot:scopedContentFingerprint(d,['a']),allowStaged:true,expectedAuthorization:failure.commitAuthorization});assert.equal(record.baseHead,base);assert.equal(record.acceptedPaths[0],'a');});
test('authorized failed-hook retry preserves both rename paths',t=>{
 const d=repo(t);mkdirSync(join(d,'scope'));writeFileSync(join(d,'scope','old.txt'),'value\n');execFileSync('git',['-C',d,'add','scope']);execFileSync('git',['-C',d,'-c','user.name=T','-c','user.email=t@x','commit','-qm','old']);renameSync(join(d,'scope','old.txt'),join(d,'scope','new.txt'));
 const hook=join(d,'.git','hooks','pre-commit');writeFileSync(hook,'#!/bin/sh\nexit 1\n');chmodSync(hook,0o755);const base=execFileSync('git',['-C',d,'rev-parse','HEAD'],{encoding:'utf8'}).trim();const snapshot=scopedContentFingerprint(d,['scope/']);let failure;
 assert.throws(()=>commitApprovedTask(d,{changeType:'feature',title:'Rename retry',files:['scope/'],expectedHead:base,snapshot}),error=>{failure=error;return Boolean(error.commitAuthorization);});assert.deepEqual(failure.commitAuthorization.paths,['scope/new.txt','scope/old.txt']);
 rmSync(hook);const record=commitApprovedTask(d,{changeType:'feature',title:'Rename retry',files:['scope/'],expectedHead:base,snapshot,allowStaged:true,expectedAuthorization:failure.commitAuthorization});assert.deepEqual(record.acceptedPaths,['scope/new.txt','scope/old.txt']);
});
test('prepared authorization rejects a same-HEAD switch to a foreign branch before commit',t=>{
 const d=repo(t);execFileSync('git',['-C',d,'branch','foreign']);writeFileSync(join(d,'a'),'changed\n');const base=execFileSync('git',['-C',d,'rev-parse','HEAD'],{encoding:'utf8'}).trim();const snapshot=scopedContentFingerprint(d,['a']);
 assert.throws(()=>commitApprovedTask(d,{changeType:'feature',title:'Branch race',files:['a'],expectedHead:base,snapshot,onPrepared:()=>execFileSync('git',['-C',d,'switch','-q','foreign'])}),error=>error.commitOwnershipInvalid===true&&/branch|ownership/i.test(error.message));
 assert.equal(execFileSync('git',['-C',d,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),base);assert.equal(execFileSync('git',['-C',d,'log','-1','--format=%s'],{encoding:'utf8'}).trim(),'base');
});
test('prepared authorization rejects changed HEAD and content before commit',t=>{
 for(const race of ['head','content']) {
  const d=repo(t);let other;
  if(race==='head') {execFileSync('git',['-C',d,'switch','-q','-c','other']);writeFileSync(join(d,'other'),'other\n');execFileSync('git',['-C',d,'add','other']);execFileSync('git',['-C',d,'-c','user.name=T','-c','user.email=t@x','commit','-qm','other']);other=execFileSync('git',['-C',d,'rev-parse','HEAD'],{encoding:'utf8'}).trim();execFileSync('git',['-C',d,'switch','-q','main']);}
  writeFileSync(join(d,'a'),'changed\n');const base=execFileSync('git',['-C',d,'rev-parse','HEAD'],{encoding:'utf8'}).trim();const snapshot=scopedContentFingerprint(d,['a']);
  assert.throws(()=>commitApprovedTask(d,{changeType:'feature',title:'Prepared race',files:['a'],expectedHead:base,snapshot,onPrepared:()=>race==='head'?execFileSync('git',['-C',d,'update-ref','HEAD',other]):writeFileSync(join(d,'a'),'raced\n')}),error=>race==='head'?error.commitOwnershipInvalid===true:error.commitAuthorizationInvalid===true);
  const after=execFileSync('git',['-C',d,'rev-parse','HEAD'],{encoding:'utf8'}).trim();if(race==='head')assert.notEqual(after,base);else assert.equal(after,base);
 }
});
test('successful hook mutation is never adopted as a clean delivery commit',t=>{const d=repo(t);writeFileSync(join(d,'a'),'changed\n');const hook=join(d,'.git','hooks','pre-commit');writeFileSync(hook,'#!/bin/sh\nprintf "pre-hook mutation\\n" > a\ngit add -- a\n');chmodSync(hook,0o755);const base=execFileSync('git',['-C',d,'rev-parse','HEAD'],{encoding:'utf8'}).trim();assert.throws(()=>commitApprovedTask(d,{changeType:'feature',title:'Pre hook',files:['a'],expectedHead:base,snapshot:scopedContentFingerprint(d,['a'])}),error=>error.commitCompleted===true);assert.notEqual(execFileSync('git',['-C',d,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),base);});
test('post-commit branch switch and foreign parent lineage are never adopted',t=>{
 for(const race of ['branch','parent']) {
  const d=repo(t),hook=join(d,'.git','hooks','post-commit');let script;
  if(race==='branch') {execFileSync('git',['-C',d,'branch','foreign']);script='#!/bin/sh\ngit switch -q foreign\n';}
  else {const tree=execFileSync('git',['-C',d,'write-tree'],{encoding:'utf8'}).trim();const orphan=execFileSync('git',['-C',d,'-c','user.name=T','-c','user.email=t@x','commit-tree',tree,'-m','orphan'],{encoding:'utf8'}).trim();script=`#!/bin/sh\ngit update-ref HEAD ${orphan}\n`;}
  writeFileSync(hook,script);chmodSync(hook,0o755);writeFileSync(join(d,'a'),'changed\n');const base=execFileSync('git',['-C',d,'rev-parse','HEAD'],{encoding:'utf8'}).trim();
  assert.throws(()=>commitApprovedTask(d,{changeType:'feature',title:'Post ownership',files:['a'],expectedHead:base,snapshot:scopedContentFingerprint(d,['a'])}),error=>error.commitCompleted===true&&new RegExp(race==='branch'?'branch':'parent').test(error.message));
 }
});
test('post-commit hook mutations leave an unadopted dirty result',t=>{const d=repo(t);writeFileSync(join(d,'a'),'changed\n');const hook=join(d,'.git','hooks','post-commit');writeFileSync(hook,'#!/bin/sh\nprintf "post-hook mutation\\n" > a\n');chmodSync(hook,0o755);const base=execFileSync('git',['-C',d,'rev-parse','HEAD'],{encoding:'utf8'}).trim();assert.throws(()=>commitApprovedTask(d,{changeType:'feature',title:'Post hook',files:['a'],expectedHead:base,snapshot:scopedContentFingerprint(d,['a'])}),error=>error.commitCompleted===true);});
test('successful hook staging an outside path is rejected before adoption',t=>{const d=repo(t);writeFileSync(join(d,'outside'),'baseline\n');execFileSync('git',['-C',d,'add','outside']);execFileSync('git',['-C',d,'-c','user.name=T','-c','user.email=t@x','commit','-qm','outside']);writeFileSync(join(d,'a'),'changed\n');const hook=join(d,'.git','hooks','pre-commit');writeFileSync(hook,'#!/bin/sh\nprintf "hook outside\\n" > outside\ngit add -- outside\n');chmodSync(hook,0o755);const base=execFileSync('git',['-C',d,'rev-parse','HEAD'],{encoding:'utf8'}).trim();assert.throws(()=>commitApprovedTask(d,{changeType:'feature',title:'Outside hook',files:['a'],expectedHead:base,snapshot:scopedContentFingerprint(d,['a'])}),error=>error.commitCompleted===true&&/path set/.test(error.message));});
test('public schema leaves changeType optional for review plans',()=>{const source=readFileSync('extensions/delivery/index.ts','utf8');assert.match(source,/changeType:\s*Type\.Optional/);});
test('existing non-default branch can continue without creating another branch',t=>{const d=repo(t);execFileSync('git',['-C',d,'switch','-q','-c','feature/existing']);assert.equal(branchState(d).branch,'feature/existing');writeFileSync(join(d,'a'),'branch change\n');const record=commitApprovedTask(d,{changeType:'feature',title:'Existing branch',files:['a'],expectedHead:branchState(d).head,snapshot:scopedContentFingerprint(d,['a'])});assert.equal(record.branch,'feature/existing');});
